# Basic Tensors

In this ungraded lab, you will try some of the basic operations you can perform on tensors.

## Imports

In [1]:
try:
    # %tensorflow_version only exists in Colab.
    %tensorflow_version 2.x
except Exception:
    pass

import tensorflow as tf
import numpy as np

## Exercise on basic Tensor operations

Lets create a single dimension numpy array on which you can perform some operation. You'll make an array of size 25, holding values from 0 to 24.

In [2]:
# Create a 1D uint8 NumPy array comprising of first 25 natural numbers
x = np.arange(0, 25)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

Now that you have your 1-D array, next you'll change that array into a `tensor`. After running the code block below, take a moment to inspect the information of your tensor.

In [7]:
# Convert NumPy array to Tensor using `tf.constant`
x = tf.constant(x)
x

<tf.Tensor: shape=(25,), dtype=int32, numpy=
array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])>

As the first operation to be performed, you'll square (element-wise) all the values in the tensor `x`

In [8]:
# Square the input tensor x
x = tf.square(x)
x

<tf.Tensor: shape=(25,), dtype=int32, numpy=
array([     0,      1,     16,     81,    256,    625,   1296,   2401,
         4096,   6561,  10000,  14641,  20736,  28561,  38416,  50625,
        65536,  83521, 104976, 130321, 160000, 194481, 234256, 279841,
       331776])>

One feature of tensors is that they can be reshaped. When reshpaing, make sure you consider dimensions that will include all of the values of the tensor.

In [9]:
# Reshape tensor x into a 5 x 5 matrix. 
x = tf.reshape(x, (5, 5))
x

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[     0,      1,     16,     81,    256],
       [   625,   1296,   2401,   4096,   6561],
       [ 10000,  14641,  20736,  28561,  38416],
       [ 50625,  65536,  83521, 104976, 130321],
       [160000, 194481, 234256, 279841, 331776]])>

Notice that you'll get an error message if you choose a shape that cannot be exactly filled with the values of the given tensor.  
* Run the cell below and look at the error message
* Try to change the tuple that is passed to `shape` to avoid an error.

In [10]:
# Try this and look at the error
# Try to change the input to `shape` to avoid an error
tmp = tf.constant([1,2,3,4])
tf.reshape(tmp, shape=(2,3))

InvalidArgumentError: {{function_node __wrapped__Reshape_device_/job:localhost/replica:0/task:0/device:CPU:0}} Input to reshape is a tensor with 4 values, but the requested shape has 6 [Op:Reshape]

Like reshaping, you can also change the data type of the values within the tensor. Run the cell below to change the data type from `int` to `float`

In [11]:
# Cast tensor x into float32. Notice the change in the dtype.
x = tf.cast(x, tf.float32)
x

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0.00000e+00, 1.00000e+00, 1.60000e+01, 8.10000e+01, 2.56000e+02],
       [6.25000e+02, 1.29600e+03, 2.40100e+03, 4.09600e+03, 6.56100e+03],
       [1.00000e+04, 1.46410e+04, 2.07360e+04, 2.85610e+04, 3.84160e+04],
       [5.06250e+04, 6.55360e+04, 8.35210e+04, 1.04976e+05, 1.30321e+05],
       [1.60000e+05, 1.94481e+05, 2.34256e+05, 2.79841e+05, 3.31776e+05]],
      dtype=float32)>

Next, you'll create a single value float tensor by the help of which you'll see `broadcasting` in action

In [12]:
# Let's define a constant and see how broadcasting works in the following cell.
y = tf.constant(2, dtype=tf.float32)
y

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

Multiply the tensors `x` and `y` together, and notice how multiplication was done and its result.

In [13]:
# Multiply tensor `x` and `y`. `y` is multiplied to each element of x.
result = tf.multiply(x, y)
result

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0.00000e+00, 2.00000e+00, 3.20000e+01, 1.62000e+02, 5.12000e+02],
       [1.25000e+03, 2.59200e+03, 4.80200e+03, 8.19200e+03, 1.31220e+04],
       [2.00000e+04, 2.92820e+04, 4.14720e+04, 5.71220e+04, 7.68320e+04],
       [1.01250e+05, 1.31072e+05, 1.67042e+05, 2.09952e+05, 2.60642e+05],
       [3.20000e+05, 3.88962e+05, 4.68512e+05, 5.59682e+05, 6.63552e+05]],
      dtype=float32)>

Re-Initialize `y` to a tensor having more values.

In [14]:
# Now let's define an array that matches the number of row elements in the `x` array.
y = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
y

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 2., 3., 4., 5.], dtype=float32)>

In [15]:
# Let's see first the contents of `x` again.
x

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0.00000e+00, 1.00000e+00, 1.60000e+01, 8.10000e+01, 2.56000e+02],
       [6.25000e+02, 1.29600e+03, 2.40100e+03, 4.09600e+03, 6.56100e+03],
       [1.00000e+04, 1.46410e+04, 2.07360e+04, 2.85610e+04, 3.84160e+04],
       [5.06250e+04, 6.55360e+04, 8.35210e+04, 1.04976e+05, 1.30321e+05],
       [1.60000e+05, 1.94481e+05, 2.34256e+05, 2.79841e+05, 3.31776e+05]],
      dtype=float32)>

Add the tensors `x` and `y` together, and notice how addition was done and its result.

In [16]:
# Add tensor `x` and `y`. `y` is added element wise to each row of `x`.
result = x + y
result

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1.00000e+00, 3.00000e+00, 1.90000e+01, 8.50000e+01, 2.61000e+02],
       [6.26000e+02, 1.29800e+03, 2.40400e+03, 4.10000e+03, 6.56600e+03],
       [1.00010e+04, 1.46430e+04, 2.07390e+04, 2.85650e+04, 3.84210e+04],
       [5.06260e+04, 6.55380e+04, 8.35240e+04, 1.04980e+05, 1.30326e+05],
       [1.60001e+05, 1.94483e+05, 2.34259e+05, 2.79845e+05, 3.31781e+05]],
      dtype=float32)>

### The shape parameter for tf.constant

When using `tf.constant()`, you can pass in a 1D array (a vector) and set the `shape` parameter to turn this vector into a multi-dimensional array.

In [17]:
tf.constant([1,2,3,4], shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

### The shape parameter for tf.Variable

Note, however, that for `tf.Variable()`, the shape of the tensor is derived from the shape given by the input array.  Setting `shape` to something other than `None` will not reshape a 1D array into a multi-dimensional array, and will give a `ValueError`.

In [18]:
try:
    # This will produce a ValueError
    tf.Variable([1,2,3,4], shape=(2,2))
except ValueError as v:
    # See what the ValueError says
    print(v)

In this `tf.Variable` creation, the initial value's shape ((4,)) is not compatible with the explicitly supplied `shape` argument ((2, 2)).
